# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vGZXUuYwgRUVPwKYO60o7bycwZyBcraw
"""

import os
import pandas as pd
import json
from pandas import json_normalize


airport_codes = ['ATL', 'CLT', 'DEN', 'DFW', 'EWR', 'IAH', 'JFK', 'LAS', 'LAX', 'MCO', 'MIA', 'ORD', 'PHX', 'SEA', 'SFO']

def load_weather_data(airport_code, year, month):
    weather_file_path = f'sample_data/{airport_code}/{year}-{month}.json'

    with open(weather_file_path) as f:
        json_data = json.load(f)


    weather_data = json_normalize(json_data['data']['weather'])


    weather_data['date'] = pd.to_datetime(weather_data['date'], errors='coerce')


    columns_with_suffix = [f"{col}_{airport_code}" if col != "date" else col for col in weather_data.columns]
    columns_mapping = dict(zip(weather_data.columns, columns_with_suffix))


    weather_data.rename(columns=columns_mapping, inplace=True)

    return weather_data

merged_data = pd.DataFrame()

for year in ['2016','2017']:
    for month in range(1, 13):
        flight_file_path = f'On_Time_On_Time_Performance_{year}_{month}.csv'

        flight_data = pd.read_csv(flight_file_path)
        flight_columns = ['FlightDate', 'Quarter', 'Year', 'Month', 'DayofMonth', 'DepTime', 'DepDel15', 'CRSDepTime',
                           'DepDelayMinutes', 'Origin', 'Dest', 'ArrTime', 'CRSArrTime', 'ArrDel15', 'ArrDelayMinutes']
        flight_data = flight_data[flight_columns]

        flight_data['FlightDate'] = pd.to_datetime(flight_data['FlightDate'], format='%d-%m-%Y', errors='coerce')

        for airport_code in airport_codes:
            weather_data = load_weather_data(airport_code, year, month)

            weather_date_column = f'date_{airport_code}'

            temp_merged_data = pd.merge(flight_data, weather_data,
                                        left_on='FlightDate',
                                        right_on='date',
                                        how='left',
                                        suffixes=('_Origin', '_Dest'))

            merged_data = pd.concat([merged_data, temp_merged_data], ignore_index=True)

columns_to_keep = ['FlightDate', 'Quarter', 'Year', 'Month', 'DayofMonth', 'DepTime', 'DepDel15','CRSDepTime', 'DepDelayMinutes', 'Origin', 'Dest', 'ArrTime', 'CRSArrTime', 'ArrDel15','ArrDelayMinutes']

merged_data = merged_data[columns_to_keep]

merged_data.to_csv('merged_data.csv', index=False)

